version: "3"
services:
    db:
        container_name: blag_db
        restart: always
        image: psql
        build:
            context: ./db
        volumes:
            - ./db/data/:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=blag
        networks:
            - network
        ports:
            - 5432:5432

    redis:
        container_name: blag_redis
        restart: always
        image: redis
        build:
            context: ./redis
        volumes:
            - ./redis/data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - network
        ports:
            - 6379:6379

    graphql:
        container_name: blag_graphql
        restart: always
        image: graphql
        build:
            context: ./graphql
        volumes:
            - ./graphql/:/usr/src/app
        environment:
            - DATABASE_URL=postgres://postgres:password@db:5432/blag
            - NEW_RELIC_LICENSE_KEY=redacted
        depends_on:
            - db
            - redis
        networks:
            - network
        ports:
            - 4000:4000

    react:
        container_name: blag_react
        restart: always
        image: react
        build:
            context: ./react
        volumes:
            - ./react/:/usr/src/app
        depends_on:
            - db
            - redis
            - graphql
        networks:
            - network
        ports:
            - 3000:3000
        # A fix for react-scripts 3.4.1 failing in Docker
        tty: true

networks:
    network:

volumes:
    db:
